"""Dependency-free access to the EMBED V2 feature catalog."""

from .catalog import (
    AnalysisAlternative,
    AnalysisDecision,
    AnalysisPattern,
    Binding,
    Catalog,
    CatalogAmbiguousError,
    CatalogError,
    CatalogLoadError,
    CatalogNotFoundError,
    CatalogValidationError,
    ClinicalContext,
    Concept,
    ContextClaim,
    ContextSource,
    ContextTableReference,
    KeyCandidate,
    ProhibitedShortcut,
    Relationship,
    RelationshipEndpoint,
    TableSpec,
    Vocabulary,
    WorkflowStep,
    load_catalog,
)

__all__ = [
    "AnalysisAlternative",
    "AnalysisDecision",
    "AnalysisPattern",
    "Binding",
    "Catalog",
    "CatalogAmbiguousError",
    "CatalogError",
    "CatalogLoadError",
    "CatalogNotFoundError",
    "CatalogValidationError",
    "ClinicalContext",
    "Concept",
    "ContextClaim",
    "ContextSource",
    "ContextTableReference",
    "KeyCandidate",
    "ProhibitedShortcut",
    "Relationship",
    "RelationshipEndpoint",
    "TableSpec",
    "Vocabulary",
    "WorkflowStep",
    "load_catalog",
]
